### PR TITLE
implements draw methods with opencv

### PR DESCRIPTION
**Pull request by lgvaz**

### CODE REVIEW

**Comment by lgvaz** [comment]
@ai-fast-track the only function we should need to change to fix the ugly labels is `_draw_label`

**Comment by oke-aditya** [comment]
Can this be done later switched with native torchvision as they are going to implement drawing boxes etc.

**Comment by lgvaz** [comment]
@oke-aditya Even if they start supporting it natively it's something we want to control ourselves.

There is no reason to depend on their code for this.

**Comment by oke-aditya** [comment]
Right. Does this makes open-cv an additional dependency ?

I guess a soft one though

**Comment by lgvaz** [comment]
open-cv was already a dependency =), this can make matplotlib optional now heh

**Pull request merged**
